[book]
authors = ["Видул Петров"]
src = "src"
title = "ТЕОРИЯ НА ПРАВОТО"
language = "bg"

# Добавете това за промяна на темата:
[output.html]
default-theme = "rust" # Може да бъде: light, rust, coal, navy, ayu
preferred-dark-theme = "rust"
additional-css = ["src/custom.css", "theme/custom.css"]

[output.html.search]
enable = true
# logical-word-separator = "[\\s,\\.:;!?()\"'-]+"
